default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: post_db_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: post_db_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: post_db_prod
